services:
  db:
    image: keinos/sqlite3
    container_name: sqlite3_db
    working_dir: /workspace
    stdin_open: true
    tty: true
    volumes:
      - ./data:/workspace
    networks:
      - app_network

  app:
    build: .
    container_name: init_db
    working_dir: /usr/src/app
    depends_on:
      - db
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - app_network
    command: ["python", "init_db.py"]

networks:
  app_network:
